name: SilenceRegion
main: com.example.slienceregion.SlienceregionPlugin
version: 1.0
api-version: "1.21"
softdepend: [WorldEdit, FastAsyncWorldEdit]
commands:
  sr:
    description: 区域静音管理
    usage: /sr <create|delete|list|info|types|reload> …
permissions:
  silenceregion.*:
    description: 拥有所有 SilenceRegion 权限
    default: op
    children:
      silenceregion.create: true
      silenceregion.delete: true
      silenceregion.list: true
      silenceregion.info: true
      silenceregion.types: true
      silenceregion.reload: true
  silenceregion.create:
    description: 创建静音区域
    default: op
  silenceregion.delete:
    description: 删除静音区域
    default: op
  silenceregion.list:
    description: 查看区域列表
    default: true
  silenceregion.info:
    description: 查看区域详情
    default: true
  silenceregion.types:
    description: 修改区域静音类型
    default: op
  silenceregion.reload:
    description: 重载配置文件
    default: op
